apiVersion: v1
kind: Secret
metadata:
  name: menuguru-secret
data:
  mysql_user: {{ .Values.mysql_user }}
  mysql_password: {{ .Values.mysql_password }}
  payment_user_id: "{{ .Values.{payment_userId }}"
  payment_access_token: {{ .Values.payment_accessToken }}  