#Caso esteja executando com o Autoscaling desabilitado, especifique o número de replicas
replicaCount: 1

image:
  tag: "${VERSION}"

service:
  #Para executar de forma local, altere o "type" para "NodePort"
  type: LoadBalancer
  port: 80
  cloud: aws

autoscaling:
  #Para habilitar o autoscaling, altere a variavel "enable" para "true" ("replicaCount" será ignorado)
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
  
#Configurações da instância MySQL
mysqlUrl: ${MYSQL_URL}
mysqlPort: ${MYSQL_PORT}
mysql_user: ${MYSQL_USER}
mysql_password: ${MYSQL_PASSWORD}

#Configurações do provedor autenticação (AWS Cognito)
aws_cognito_user_pool_id: ${AWS_COGNITO_USER_POOL_ID64}
aws_region: ${AWS_REGION}