apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-deployment
  labels:
    menuguru.fiapprj.perisatto.com/name: user-management
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      menuguru.fiapprj.perisatto.com/name: user-management
  template:
    metadata:
      name: user-management-deployment
      labels:
        menuguru.fiapprj.perisatto.com/name: user-management
    spec:           
      containers:
        - name: user-management-service
          image: rperisatto/user-management:{{ .Values.image.tag }}
          env:
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: user-management-config
                  key: mysql_url
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: mysql_user      
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: mysql_password
            - name: AWS_COGNITO_USER_POOL_ID
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: aws_cognito_user_pool_id
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: user-management-config
                  key: aws_region                                    
          ports:
            - containerPort: 8080      
          readinessProbe:
            httpGet:
              path: /user-management/v1/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /user-management/v1/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60
