apiVersion: v1
kind: Secret
metadata:
  name: user-management-secret
data:
  mysql_user: {{ .Values.mysql_user }}
  mysql_password: {{ .Values.mysql_password }}
  aws_cognito_user_pool_id: "{{ .Values.aws_cognito_user_pool_id }}"